name: Gawe for .NET

on:
  workflow_call:

jobs:
  dotnet:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        configuration: [Debug, Release]

    name: Build ${{ matrix.configuration }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration ${{ matrix.configuration }} --no-restore
      - name: Test
        run: dotnet test --configuration ${{ matrix.configuration }} --no-restore --verbosity normal
      # Initialize for CD
      - name: Create NuGet package
        if: github.event_name == 'push' && matrix.os == 'ubuntu-latest' && matrix.configuration == 'Release'
        run: dotnet pack --configuration ${{ matrix.configuration }} --no-build -o __out__
      - name: Upload build artifact
        if: github.event_name == 'push' && matrix.os == 'ubuntu-latest' && matrix.configuration == 'Release'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ github.sha }}
          path: |
            __out__/*.*nupkg
        
  merge:
    name: Auto-merge pull requests
    needs: [dotnet]
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && (github.actor == 'Ali-p1986' || github.actor == github.repository_owner || github.actor == 'dependabot[bot]')
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Automatically merge the trusted PR from ${{ github.actor }}
        run: gh pr merge --auto -d -r "$PR_URL"

  deploy:
    name: Deploy NuGet package
    needs: [dotnet]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ github.sha }}
      - name: Deploy Github package
        run: |
          dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          dotnet nuget push *.*nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
      
