name: Gawe for .NET

on:
  workflow_call:
    inputs:
      nuget-deploy:
        description: Deploy generated packages to the NuGet galley
        type: boolean
        default: true
        required: false
      nuget-deploy-branch:
        description: Determines the release branch for NuGet packages
        type: string
        required: false
        default: master
      trusted-user:
          description: Name of the trusted account for auto-merge the PRs
          type: string
          required: false
          default: Ali-p1986

    secrets:
      NUGET_API_KEY:
          description: Nuget gallery API key
          required: false

jobs:
  dotnet:
    strategy:
      matrix:
        os: [windows, ubuntu, macos]
        configuration: [Debug, Release]

    name: Build ${{ matrix.configuration }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration ${{ matrix.configuration }} --no-restore
      - name: Test
        run: dotnet test --configuration ${{ matrix.configuration }} --no-restore --verbosity normal
      # Initialize for CD
      - name: Create NuGet package
        if: matrix.os == 'ubuntu' && matrix.configuration == 'Release' && github.event_name != 'pull_request'
        run: dotnet pack --configuration ${{ matrix.configuration }} --no-build -o __out__
      - name: Upload build artifact
        if: matrix.os == 'ubuntu' && matrix.configuration == 'Release' && github.event_name != 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ github.sha }}
          path: |
            __out__/*.*nupkg
        
  merge:
    name: Auto-merge trusted PRs
    needs: [dotnet]
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && (github.actor == inputs.trusted-user || github.actor == github.repository_owner || github.actor == 'dependabot[bot]')
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Automatically merge the trusted PR from ${{ github.actor }}
        run: gh pr merge --auto -r -d "$PR_URL"

  deploy:
    name: Deploy NuGet package
    needs: [dotnet]
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ github.sha }}
      - name: Deploy to Github packages
        continue-on-error: true
        run: |
          dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          dotnet nuget push *.*nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate
        shell: bash
      - name: Deploy to NuGet gallery
        if: inputs.nuget-deploy && github.ref_name == inputs.nuget-deploy-branch
        continue-on-error: true
        run: dotnet nuget push *.*nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source "nuget.org" --skip-duplicate
        shell: bash
        
      
